[tool.mypy]
exclude = [ "tests" ]
namespace_packages = true

[[tool.mypy.overrides]]
module = [
    'asyncpg', 'pypika'
]
ignore_missing_imports = true

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = 'function'

[tool.flake8]
max-line-length = 88
ignore = [
    'W293','E128','E124','E741','W504','W503','E704','E701','F401','F403','E241'
]
exclude = [
    '.venv', 'tests', 'migrate.py'
]
