[tool.mypy]
exclude = [ "tests" ]
namespace_packages = true

[[tool.mypy.overrides]]
module = [
    'asyncpg', 'pypika', 'dotenv'
]
ignore_missing_imports = true

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = 'function'

[tool.ruff]
line-length = 88
indent-width = 4
target-version = 'py313'

[tool.ruff.lint]
ignore = ['F403']

[tool.ruff.format]
quote-style = "single"
