name: Test and lint

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [ "3.11", "3.12", "3.13" ]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install flake8 Flake8-pyproject
            - name: Lint check
              run: |
                flake8 -v app

    type-check:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [ "3.11", "3.12", "3.13" ]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install mypy
            - name: Type check
              run: |
                mypy app

    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [ "3.11", "3.12", "3.13" ]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest pytest-asyncio coverage
            - name: Run tests
              run: |
                python -m coverage run -m pytest -s -v tests
            - name: Upload coverage artifact
              uses: actions/upload-artifact@v3
              with:
                name: coverage-report
                path: .coverage

    coverage:
        runs-on: ubuntu-latest
        needs: test
        strategy:
            matrix:
                python-version: [ "3.11", "3.12", "3.13" ]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install coverage
            - name: Check coverage
              run: |
                python -m coverage report -m
